[project]
name = "sync-search-tool"
authors = ["sync-search-dev"]
description = "Decentralized search request and index management platform"
telemetry = false
requirements = []
[contracts.sync-search-manager]
path = "contracts/sync-search-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
